/-
Copyright (c) 2026 Idris Ali Shaik. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik
-/
import FirstPassageLinearTransport.AdjustableBarrierDensity
import FirstPassageLinearTransport.EntropyBarrier

/-!
# Adjustable barrier entropy rate

This one-definition module is shared by the canonical endpoint-parameter
selection and the retained legacy two-regime profile.  It prevents either
consumer from importing the other's execution and aggregation machinery.
-/

namespace FirstPassageLinearTransport

noncomputable section

/-- The entropy rate generated by an adjustable barrier. -/
def adjustableEntropyRate (lambda t : ℝ) : ℝ :=
  binaryBarrierRate (adjustableBarrierDisplacement lambda t)

end

end FirstPassageLinearTransport
