/-
Copyright (c) 2026 Idris Ali Shaik. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Idris Ali Shaik
-/
import Mathlib.Analysis.SpecialFunctions.Log.Base
import FirstPassageLinearTransport.Parameters
import FirstPassageLinearTransport.VaryingDensity

/-!
# Varying-scale first-passage bootstrap

The set recurrence in this module is the literal repeated stopped-map
pullback.  Its density exponent is exactly `Dc * chi^R`; no independence or
fresh-randomness premise is introduced between stages.
-/

namespace FirstPassageLinearTransport

open scoped Real Topology BigOperators

noncomputable section

/-- Repeated stopped-map pullback, starting from the extended barrier set. -/
def bootstrapSet {r eta : ℝ} (p : StageSetup r eta) : ℕ → Set ℕ
  | 0 => extendedWindow p
  | R + 1 => firstPassagePullback p (bootstrapSet p R)

@[simp] theorem bootstrapSet_zero {r eta : ℝ} (p : StageSetup r eta) :
    bootstrapSet p 0 = extendedWindow p := rfl

theorem bootstrapSet_succ {r eta : ℝ} (p : StageSetup r eta) (R : ℕ) :
    bootstrapSet p (R + 1) = firstPassagePullback p (bootstrapSet p R) := rfl

/-- Exact density exponent after `R` linear-transport stages. -/
def bootstrapD (chi Dc : ℝ) (R : ℕ) : ℝ := Dc * chi ^ R

@[simp] theorem bootstrapD_zero (chi Dc : ℝ) :
    bootstrapD chi Dc 0 = Dc := by simp [bootstrapD]

theorem bootstrapD_succ (chi Dc : ℝ) (R : ℕ) :
    bootstrapD chi Dc (R + 1) = chi * bootstrapD chi Dc R := by
  simp [bootstrapD, pow_succ]
  ring

/-- Exact prefactor generated by repeated use of the pullback theorem. -/
def bootstrapC {r eta : ℝ} (p : StageSetup r eta)
    (chi Dc : ℝ) : ℕ → ℝ
  | 0 => quadraticWindowGlobalConstant eta
  | R + 1 =>
      pullbackGlobalConstant p chi Dc * (bootstrapC p chi Dc R + 1) *
        (bootstrapD chi Dc R)⁻¹ ^ 2

@[simp] theorem bootstrapC_zero {r eta : ℝ} (p : StageSetup r eta)
    (chi Dc : ℝ) :
    bootstrapC p chi Dc 0 = quadraticWindowGlobalConstant eta := rfl

theorem bootstrapC_succ {r eta : ℝ} (p : StageSetup r eta)
    (chi Dc : ℝ) (R : ℕ) :
    bootstrapC p chi Dc (R + 1) =
      pullbackGlobalConstant p chi Dc * (bootstrapC p chi Dc R + 1) *
        (bootstrapD chi Dc R)⁻¹ ^ 2 := rfl

theorem bootstrapD_pos {chi Dc : ℝ}
    (hchi : 0 < chi) (hDc : 0 < Dc) (R : ℕ) :
    0 < bootstrapD chi Dc R := by
  unfold bootstrapD
  positivity

theorem bootstrapD_le_Dc {chi Dc : ℝ}
    (hchi0 : 0 ≤ chi) (hchi1 : chi ≤ 1) (hDc0 : 0 ≤ Dc) (R : ℕ) :
    bootstrapD chi Dc R ≤ Dc := by
  unfold bootstrapD
  have hp : chi ^ R ≤ 1 := pow_le_one₀ hchi0 hchi1
  nlinarith [mul_le_mul_of_nonneg_left hp hDc0]

theorem bootstrapC_pos {r eta chi Dc : ℝ} (p : StageSetup r eta)
    (hchi0 : 0 < chi) (hchir : chi < r)
    (hDc0 : 0 < Dc) (hchiDc : chi * Dc < 1) :
    ∀ R, 0 < bootstrapC p chi Dc R := by
  intro R
  induction R with
  | zero =>
      simpa using (extendedWindow_powerDense p).C_pos
  | succ R ih =>
      rw [bootstrapC_succ]
      have hK : 0 < pullbackGlobalConstant p chi Dc := by
        have hnum : 0 < 2 * pullbackShellConstant p chi Dc := by
          exact mul_pos (by norm_num) (pullbackShellConstant_pos p hchir)
        have hden : 0 < 2 * Real.exp (-(chi * Dc * Real.log 2)) - 1 := by
          have hlog2 := Real.log_pos (by norm_num : (1 : ℝ) < 2)
          have hlt : -Real.log 2 < -(chi * Dc * Real.log 2) := by
            nlinarith
          have hexp := Real.exp_lt_exp.2 hlt
          rw [Real.exp_neg, Real.exp_log (by norm_num : (0 : ℝ) < 2)] at hexp
          nlinarith
        simpa [pullbackGlobalConstant] using div_pos hnum hden
      have hD := bootstrapD_pos hchi0 hDc0 R
      positivity

/-- Iterated density theorem.  The only analytic input is the already
compiled one-stage first-passage pullback theorem. -/
theorem bootstrapSet_powerDense
    {r eta chi Dc : ℝ} (p : StageSetup r eta)
    (hchi0 : 0 < chi) (hchir : chi < r) (hchi1 : chi ≤ 1)
    (hDc0 : 0 < Dc)
    (hDcRate : Dc ≤ quadraticWindowDensityRate eta)
    (hchiDc : chi * Dc < 1) :
    ∀ R, PowerDense (bootstrapSet p R)
      (bootstrapC p chi Dc R) (bootstrapD chi Dc R) := by
  intro R
  induction R with
  | zero =>
      simpa using (extendedWindow_powerDense p).degrade_exponent hDc0 hDcRate
  | succ R ih =>
      rw [bootstrapSet_succ, bootstrapC_succ, bootstrapD_succ]
      apply firstPassagePullback_powerDense p (bootstrapSet p R) ih
        hchi0 hchir hDc0
      · exact bootstrapD_le_Dc hchi0.le hchi1 hDc0.le R
      · have hmul : chi * Dc ≤ 1 * Dc :=
          mul_le_mul_of_nonneg_right hchi1 hDc0.le
        have hmul' : chi * Dc ≤ Dc := by simpa only [one_mul] using hmul
        exact hmul'.trans hDcRate
      · exact hchiDc

/-- Every positive integer lies in the shell indexed by its binary log. -/
theorem mem_dyadicShell_log {n : ℕ} (hn : 0 < n) :
    n ∈ dyadicShell (Nat.log 2 n) := by
  rw [mem_dyadicShell]
  exact ⟨Nat.pow_log_le_self 2 hn.ne',
    Nat.lt_pow_succ_log_self (by norm_num) n⟩

/-- The stopped block length never exceeds the current binary shell index. -/
theorem stageLength_le_log {r eta : ℝ} (p : StageSetup r eta)
    {n : ℕ} (hn : 0 < n) (hnW : n ∈ extendedWindow p) :
    stageLength p n ≤ Nat.log 2 n := by
  by_cases hlarge : p.M0 ≤ Nat.log 2 n
  · have hshell := mem_dyadicShell_log hn
    have hgood := mem_initialWindowGood_of_mem_extended_of_large p hnW hlarge
    exact stageLength_le_shell p hlarge hshell hgood
  · simp [stageLength, hlarge]

/-- A fixed startup constant for the totalized stopped map. -/
def stageK {r eta : ℝ} (p : StageSetup r eta) : ℝ :=
  (2 : ℝ) ^ p.M0

theorem stageK_pos {r eta : ℝ} (p : StageSetup r eta) :
    0 < stageK p := by unfold stageK; positivity

theorem stageK_one_le {r eta : ℝ} (p : StageSetup r eta) :
    1 ≤ stageK p := by
  unfold stageK
  exact one_le_pow₀ (by norm_num)

/-- One stopped stage satisfies the deterministic power contraction, with
the fixed constant only paying for the finite startup branch. -/
theorem stageMap_le_power {r eta : ℝ} (p : StageSetup r eta)
    {n : ℕ} (hn : 0 < n) (hnW : n ∈ extendedWindow p) :
    (stageMap p n : ℝ) ≤ stageK p * (n : ℝ) ^ r := by
  let M := Nat.log 2 n
  have hshell : n ∈ dyadicShell M := mem_dyadicShell_log hn
  by_cases hlarge : p.M0 ≤ M
  · have hgood := mem_initialWindowGood_of_mem_extended_of_large p hnW hlarge
    have hfp := stageLength_isFirstPassage p hlarge hshell hgood
    have hstage : (stageMap p n : ℝ) ≤ targetScale r M := by
      exact_mod_cast hfp.1
    have hrM0 : 0 ≤ r * (M : ℝ) :=
      mul_nonneg p.r_pos.le (Nat.cast_nonneg M)
    have hfloor : (⌊r * (M : ℝ)⌋₊ : ℝ) ≤ r * M :=
      Nat.floor_le hrM0
    have htarget : (targetScale r M : ℝ) ≤ (2 : ℝ) ^ (r * M) := by
      unfold targetScale
      rw [Nat.cast_pow, ← Real.rpow_natCast]
      exact Real.rpow_le_rpow_of_exponent_le (by norm_num) hfloor
    have hbase : (2 : ℝ) ^ M ≤ n := by
      exact_mod_cast (mem_dyadicShell.mp hshell).1
    have hpow : (2 : ℝ) ^ (r * M) ≤ (n : ℝ) ^ r := by
      calc
        (2 : ℝ) ^ (r * M) = (2 : ℝ) ^ ((M : ℝ) * r) := by ring_nf
        _ = ((2 : ℝ) ^ M) ^ r := by
          rw [Real.rpow_mul (by norm_num), Real.rpow_natCast]
        _ ≤ (n : ℝ) ^ r :=
          Real.rpow_le_rpow (by positivity) hbase p.r_pos.le
    have hKmul : (n : ℝ) ^ r ≤ stageK p * (n : ℝ) ^ r := by
      simpa only [one_mul] using
        mul_le_mul_of_nonneg_right (stageK_one_le p)
          (Real.rpow_nonneg (by positivity) r)
    exact hstage.trans (htarget.trans (hpow.trans hKmul))
  · have hstage : stageMap p n = n := by
      simp [stageMap, stageLength, M, hlarge]
    have hnK : (n : ℝ) ≤ stageK p := by
      have hnlt : n < 2 ^ p.M0 := by
        have hnlog : Nat.log 2 n < p.M0 := by omega
        exact (mem_dyadicShell.mp hshell).2.trans_le
          (Nat.pow_le_pow_right (by norm_num) (by omega))
      unfold stageK
      exact_mod_cast hnlt.le
    have hpow1 : 1 ≤ (n : ℝ) ^ r := by
      exact Real.one_le_rpow (by exact_mod_cast hn) p.r_pos.le
    rw [hstage]
    calc
      (n : ℝ) ≤ stageK p := hnK
      _ = stageK p * 1 := by ring
      _ ≤ stageK p * (n : ℝ) ^ r :=
        mul_le_mul_of_nonneg_left hpow1 (stageK_pos p).le

/-- Iteration of the total stopped map. -/
def stageOrbit {r eta : ℝ} (p : StageSetup r eta) : ℕ → ℕ → ℕ
  | 0, n => n
  | R + 1, n => stageOrbit p R (stageMap p n)

/-- Total shortcut time accumulated by `stageOrbit`. -/
def stageClock {r eta : ℝ} (p : StageSetup r eta) : ℕ → ℕ → ℕ
  | 0, _n => 0
  | R + 1, n => stageLength p n + stageClock p R (stageMap p n)

@[simp] theorem stageOrbit_zero {r eta : ℝ} (p : StageSetup r eta) (n : ℕ) :
    stageOrbit p 0 n = n := rfl

theorem stageOrbit_succ {r eta : ℝ} (p : StageSetup r eta) (R n : ℕ) :
    stageOrbit p (R + 1) n = stageOrbit p R (stageMap p n) := rfl

@[simp] theorem stageClock_zero {r eta : ℝ} (p : StageSetup r eta) (n : ℕ) :
    stageClock p 0 n = 0 := rfl

theorem stageClock_succ {r eta : ℝ} (p : StageSetup r eta) (R n : ℕ) :
    stageClock p (R + 1) n =
      stageLength p n + stageClock p R (stageMap p n) := rfl

/-- Concatenating stopped blocks is an exact shortcut iterate. -/
theorem stageOrbit_eq_orbit_stageClock {r eta : ℝ}
    (p : StageSetup r eta) (R n : ℕ) :
    stageOrbit p R n = orbit (stageClock p R n) n := by
  induction R generalizing n with
  | zero => simp
  | succ R ih =>
      rw [stageOrbit_succ, ih, stageClock_succ, add_comm,
        orbit_add, ← stageMap_is_actual]



/-- Earlier density exponents dominate the terminal exponent. -/
theorem bootstrapD_terminal_le {chi Dc : ℝ} {j R : ℕ}
    (hchi0 : 0 ≤ chi) (hchi1 : chi ≤ 1) (hDc0 : 0 ≤ Dc)
    (hjR : j ≤ R) :
    bootstrapD chi Dc R ≤ bootstrapD chi Dc j := by
  unfold bootstrapD
  exact mul_le_mul_of_nonneg_left
    (pow_le_pow_of_le_one hchi0 hchi1 hjR) hDc0

/-- Coarse fixed majorant for one prefactor stage. -/
def bootstrapStageK {r eta : ℝ} (p : StageSetup r eta)
    (chi Dc : ℝ) : ℝ :=
  pullbackGlobalConstant p chi Dc + 2

/-- The exact prefactor recurrence has at most quadratic logarithmic cost in
the number of stages.  This division-free statement is the form consumed by
the varying-shell proof. -/
theorem bootstrapC_terminal_bound
    {r eta chi Dc : ℝ} (p : StageSetup r eta)
    (hchi0 : 0 < chi) (hchir : chi < r) (hchi1 : chi ≤ 1)
    (hDc0 : 0 < Dc) (hDc1 : Dc ≤ 1) (hchiDc : chi * Dc < 1)
    (R : ℕ) :
    bootstrapC p chi Dc R + 2 ≤
      (quadraticWindowGlobalConstant eta + 2) *
        (bootstrapStageK p chi Dc *
          (bootstrapD chi Dc R)⁻¹ ^ 2) ^ R := by
  let F := bootstrapStageK p chi Dc * (bootstrapD chi Dc R)⁻¹ ^ 2
  have hK0 : 0 < pullbackGlobalConstant p chi Dc := by
    have hnum : 0 < 2 * pullbackShellConstant p chi Dc :=
      mul_pos (by norm_num) (pullbackShellConstant_pos p hchir)
    have hden : 0 < 2 * Real.exp (-(chi * Dc * Real.log 2)) - 1 := by
      have hlog2 := Real.log_pos (by norm_num : (1 : ℝ) < 2)
      have hlt : -Real.log 2 < -(chi * Dc * Real.log 2) := by
        nlinarith
      have hexp := Real.exp_lt_exp.2 hlt
      rw [Real.exp_neg, Real.exp_log (by norm_num : (0 : ℝ) < 2)] at hexp
      nlinarith
    simpa [pullbackGlobalConstant] using div_pos hnum hden
  have hstage1 : 1 ≤ bootstrapStageK p chi Dc := by
    unfold bootstrapStageK
    linarith
  have hDR0 := bootstrapD_pos hchi0 hDc0 R
  have hDR1 : bootstrapD chi Dc R ≤ 1 :=
    (bootstrapD_le_Dc hchi0.le hchi1 hDc0.le R).trans hDc1
  have hinv1 : 1 ≤ (bootstrapD chi Dc R)⁻¹ :=
    (one_le_inv₀ hDR0).2 hDR1
  have hinvSq : 1 ≤ (bootstrapD chi Dc R)⁻¹ ^ 2 :=
    one_le_pow₀ hinv1
  have hF1 : 1 ≤ F := by
    dsimp [F]
    exact one_le_mul_of_one_le_of_one_le hstage1 hinvSq
  have hF0 : 0 ≤ F := zero_le_one.trans hF1
  have hbaseC : 0 < quadraticWindowGlobalConstant eta :=
    (extendedWindow_powerDense p).C_pos
  have hind : ∀ j : ℕ, j ≤ R →
      bootstrapC p chi Dc j + 2 ≤
        (quadraticWindowGlobalConstant eta + 2) * F ^ j := by
    intro j hj
    induction j with
    | zero => simp
    | succ j ih =>
        have hjR : j ≤ R := by omega
        have hprev := ih hjR
        have hDj0 := bootstrapD_pos hchi0 hDc0 j
        have hterm := bootstrapD_terminal_le hchi0.le hchi1 hDc0.le hjR
        have hinv :
            (bootstrapD chi Dc j)⁻¹ ≤ (bootstrapD chi Dc R)⁻¹ :=
          (inv_le_inv₀ hDj0 hDR0).2 hterm
        have hinvSq' :
            (bootstrapD chi Dc j)⁻¹ ^ 2 ≤
              (bootstrapD chi Dc R)⁻¹ ^ 2 :=
          pow_le_pow_left₀ (inv_nonneg.mpr hDj0.le) hinv 2
        have hCj := bootstrapC_pos p hchi0 hchir hDc0 hchiDc j
        have hrec :
            bootstrapC p chi Dc (j + 1) + 2 ≤
              F * (bootstrapC p chi Dc j + 2) := by
          rw [bootstrapC_succ]
          have hC12 : bootstrapC p chi Dc j + 1 ≤
              bootstrapC p chi Dc j + 2 := by linarith
          have hprod :
              (bootstrapC p chi Dc j + 1) *
                    (bootstrapD chi Dc j)⁻¹ ^ 2 ≤
                (bootstrapC p chi Dc j + 2) *
                    (bootstrapD chi Dc R)⁻¹ ^ 2 :=
            mul_le_mul hC12 hinvSq' (by positivity) (by linarith)
          have htail :
              2 ≤ 2 * ((bootstrapD chi Dc R)⁻¹ ^ 2 *
                (bootstrapC p chi Dc j + 2)) := by
            have hcommon : 1 ≤ (bootstrapD chi Dc R)⁻¹ ^ 2 *
                (bootstrapC p chi Dc j + 2) :=
              one_le_mul_of_one_le_of_one_le hinvSq (by linarith)
            nlinarith
          dsimp [F]
          unfold bootstrapStageK
          have hfirst := mul_le_mul_of_nonneg_left hprod hK0.le
          nlinarith
        calc
          bootstrapC p chi Dc (j + 1) + 2 ≤
              F * (bootstrapC p chi Dc j + 2) := hrec
          _ ≤ F * ((quadraticWindowGlobalConstant eta + 2) * F ^ j) :=
            mul_le_mul_of_nonneg_left hprev hF0
          _ = (quadraticWindowGlobalConstant eta + 2) * F ^ (j + 1) := by
            rw [pow_succ]
            ring
  simpa [F] using hind R le_rfl

/-- Logarithmic form of the terminal prefactor bound. -/
theorem bootstrapC_exp_bound
    {r eta chi Dc : ℝ} (p : StageSetup r eta)
    (hchi0 : 0 < chi) (hchir : chi < r) (hchi1 : chi ≤ 1)
    (hDc0 : 0 < Dc) (hDc1 : Dc ≤ 1) (hchiDc : chi * Dc < 1)
    (R : ℕ) :
    bootstrapC p chi Dc R + 2 ≤ Real.exp
      (Real.log (quadraticWindowGlobalConstant eta + 2) +
        (R : ℝ) * Real.log (bootstrapStageK p chi Dc) +
        2 * (R : ℝ) * Real.log Dc⁻¹ +
        2 * (R : ℝ) ^ 2 * Real.log chi⁻¹) := by
  have hterm := bootstrapC_terminal_bound p hchi0 hchir hchi1
    hDc0 hDc1 hchiDc R
  let B := quadraticWindowGlobalConstant eta + 2
  let S := bootstrapStageK p chi Dc
  let D := bootstrapD chi Dc R
  have hB : 0 < B := by dsimp [B]; linarith [(extendedWindow_powerDense p).C_pos]
  have hS : 0 < S := by
    dsimp [S, bootstrapStageK]
    have hnum : 0 < 2 * pullbackShellConstant p chi Dc :=
      mul_pos (by norm_num) (pullbackShellConstant_pos p hchir)
    have hden : 0 < 2 * Real.exp (-(chi * Dc * Real.log 2)) - 1 := by
      have hlog2 := Real.log_pos (by norm_num : (1 : ℝ) < 2)
      have hlt : -Real.log 2 < -(chi * Dc * Real.log 2) := by nlinarith
      have hexp := Real.exp_lt_exp.2 hlt
      rw [Real.exp_neg, Real.exp_log (by norm_num : (0 : ℝ) < 2)] at hexp
      nlinarith
    have hK : 0 < pullbackGlobalConstant p chi Dc := by
      simpa [pullbackGlobalConstant] using div_pos hnum hden
    linarith
  have hD : 0 < D := by dsimp [D]; exact bootstrapD_pos hchi0 hDc0 R
  have hRHS : 0 < B * (S * D⁻¹ ^ 2) ^ R := by positivity
  have hlog : Real.log (B * (S * D⁻¹ ^ 2) ^ R) =
      Real.log B + (R : ℝ) * Real.log S +
        2 * (R : ℝ) * Real.log Dc⁻¹ +
        2 * (R : ℝ) ^ 2 * Real.log chi⁻¹ := by
    have hDcne := hDc0.ne'
    have hchine := hchi0.ne'
    have hDform : D⁻¹ = Dc⁻¹ * (chi⁻¹) ^ R := by
      dsimp [D, bootstrapD]
      rw [mul_inv, inv_pow]
    rw [Real.log_mul hB.ne' (pow_ne_zero R (mul_ne_zero hS.ne'
        (pow_ne_zero 2 (inv_ne_zero hD.ne')))),
      Real.log_pow, Real.log_mul hS.ne' (pow_ne_zero 2 (inv_ne_zero hD.ne')),
      Real.log_pow, hDform,
      Real.log_mul (inv_ne_zero hDcne) (pow_ne_zero R (inv_ne_zero hchine)),
      Real.log_pow]
    push_cast
    ring
  apply hterm.trans
  apply (Real.log_le_iff_le_exp hRHS).1
  rw [hlog]


/-- Coarse all-stage contraction.  The factor `stageK^R` is deliberately
weaker than the paper's bounded geometric factor, but remains only
polynomial on the logarithmic stage schedule and is easier to audit. -/
theorem stageOrbit_le_power
    {r eta : ℝ} (p : StageSetup r eta) {R n : ℕ}
    (hn : 0 < n) (hnSet : n ∈ bootstrapSet p R) :
    (stageOrbit p R n : ℝ) ≤
      stageK p ^ R * (n : ℝ) ^ (r ^ R) := by
  induction R generalizing n with
  | zero => simp
  | succ R ih =>
      rw [bootstrapSet_succ] at hnSet
      have hnW : n ∈ extendedWindow p := hnSet.1
      have hmapSet : stageMap p n ∈ bootstrapSet p R := hnSet.2
      have hmapPos : 0 < stageMap p n := by
        rw [stageMap_is_actual]
        exact orbit_pos hn _
      have hIH := ih hmapPos hmapSet
      have hstage := stageMap_le_power p hn hnW
      have hr0 : 0 ≤ r := p.r_pos.le
      have hr1 : r ≤ 1 := p.r_lt_one.le
      have hrPow0 : 0 ≤ r ^ R := pow_nonneg hr0 _
      have hrPow1 : r ^ R ≤ 1 := pow_le_one₀ hr0 hr1
      have hraise :
          (stageMap p n : ℝ) ^ (r ^ R) ≤
            (stageK p * (n : ℝ) ^ r) ^ (r ^ R) :=
        Real.rpow_le_rpow (by positivity) hstage hrPow0
      have hKpow : stageK p ^ (r ^ R) ≤ stageK p := by
        have hlog := Real.rpow_le_rpow_of_exponent_le
          (stageK_one_le p) hrPow1
        simpa [Real.rpow_one] using hlog
      rw [stageOrbit_succ]
      calc
        (stageOrbit p R (stageMap p n) : ℝ) ≤
            stageK p ^ R * (stageMap p n : ℝ) ^ (r ^ R) := hIH
        _ ≤ stageK p ^ R *
            (stageK p * (n : ℝ) ^ r) ^ (r ^ R) :=
          mul_le_mul_of_nonneg_left hraise
            (pow_nonneg (stageK_pos p).le R)
        _ = stageK p ^ R *
            (stageK p ^ (r ^ R) *
              ((n : ℝ) ^ r) ^ (r ^ R)) := by
          rw [Real.mul_rpow (stageK_pos p).le (by positivity)]
        _ ≤ stageK p ^ R *
            (stageK p * ((n : ℝ) ^ r) ^ (r ^ R)) := by
          exact mul_le_mul_of_nonneg_left
            (mul_le_mul_of_nonneg_right hKpow (by positivity))
            (pow_nonneg (stageK_pos p).le R)
        _ = stageK p ^ (R + 1) * (n : ℝ) ^ (r ^ (R + 1)) := by
          rw [pow_succ, pow_succ, ← Real.rpow_mul (by positivity)]
          ring

/-- Geometric clock coefficient in the recursive orientation of
`stageOrbit`. -/
def clockGeom (r : ℝ) : ℕ → ℝ
  | 0 => 0
  | R + 1 => 1 + r * clockGeom r R

theorem clockGeom_nonneg {r : ℝ} (hr : 0 ≤ r) :
    ∀ R, 0 ≤ clockGeom r R := by
  intro R
  induction R with
  | zero => simp [clockGeom]
  | succ R ih => simp only [clockGeom]; positivity

theorem clockGeom_le_nat {r : ℝ} (hr0 : 0 ≤ r) (hr1 : r ≤ 1) :
    ∀ R, clockGeom r R ≤ R := by
  intro R
  induction R with
  | zero => simp [clockGeom]
  | succ R ih =>
      rw [clockGeom]
      have hnonneg := clockGeom_nonneg hr0 R
      have hmul : r * clockGeom r R ≤ clockGeom r R :=
        mul_le_of_le_one_left hnonneg hr1
      push_cast
      linarith

/-- The accumulated shortcut clock has the expected geometric leading term;
the deliberately coarse startup error is only quadratic in the stage count. -/
theorem stageClock_le_logb
    {r eta : ℝ} (p : StageSetup r eta) {R n : ℕ}
    (hn : 0 < n) (hnSet : n ∈ bootstrapSet p R) :
    (stageClock p R n : ℝ) ≤
      clockGeom r R * Real.logb 2 n +
        (R : ℝ) ^ 2 * Real.logb 2 (stageK p) := by
  induction R generalizing n with
  | zero => simp [clockGeom]
  | succ R ih =>
      rw [bootstrapSet_succ] at hnSet
      have hnW := hnSet.1
      have hmapSet := hnSet.2
      have hmapPos : 0 < stageMap p n := by
        rw [stageMap_is_actual]
        exact orbit_pos hn _
      have hlenNat := stageLength_le_log p hn hnW
      have hlenCast : (stageLength p n : ℝ) ≤ (Nat.log 2 n : ℝ) := by
        exact_mod_cast hlenNat
      have hlen : (stageLength p n : ℝ) ≤ Real.logb 2 n :=
        hlenCast.trans (Real.natLog_le_logb n 2)
      have hIH := ih hmapPos hmapSet
      have hstage := stageMap_le_power p hn hnW
      have hlogMap : Real.logb 2 (stageMap p n) ≤
          Real.logb 2 (stageK p) + r * Real.logb 2 n := by
        have hmono := (Real.logb_le_logb (b := (2 : ℝ)) (by norm_num)
          (by exact_mod_cast hmapPos) (mul_pos (stageK_pos p)
            (Real.rpow_pos_of_pos (by exact_mod_cast hn) r))).2 hstage
        calc
          Real.logb 2 (stageMap p n) ≤
              Real.logb 2 (stageK p * (n : ℝ) ^ r) := hmono
          _ = Real.logb 2 (stageK p) + Real.logb 2 ((n : ℝ) ^ r) := by
            rw [Real.logb_mul (stageK_pos p).ne'
              (Real.rpow_pos_of_pos (by exact_mod_cast hn) r).ne']
          _ = Real.logb 2 (stageK p) + r * Real.logb 2 n := by
            rw [Real.logb_rpow_eq_mul_logb_of_pos (by exact_mod_cast hn)]
      have hgeom0 := clockGeom_nonneg p.r_pos.le R
      have hlogK0 : 0 ≤ Real.logb 2 (stageK p) :=
        Real.logb_nonneg (by norm_num) (stageK_one_le p)
      have hmain :
          (stageLength p n : ℝ) + (stageClock p R (stageMap p n) : ℝ) ≤
            clockGeom r (R + 1) * Real.logb 2 n +
              ((R : ℝ) + 1) ^ 2 * Real.logb 2 (stageK p) := by
        calc
        (stageLength p n : ℝ) + (stageClock p R (stageMap p n) : ℝ)
            ≤ Real.logb 2 n +
              (clockGeom r R * Real.logb 2 (stageMap p n) +
                (R : ℝ) ^ 2 * Real.logb 2 (stageK p)) :=
          add_le_add hlen hIH
        _ ≤ Real.logb 2 n +
              (clockGeom r R *
                  (Real.logb 2 (stageK p) + r * Real.logb 2 n) +
                (R : ℝ) ^ 2 * Real.logb 2 (stageK p)) := by
          gcongr
        _ ≤ clockGeom r (R + 1) * Real.logb 2 n +
              ((R : ℝ) + 1) ^ 2 * Real.logb 2 (stageK p) := by
          rw [clockGeom]
          have hR0 : (0 : ℝ) ≤ R := Nat.cast_nonneg R
          have hpay : clockGeom r R ≤ 2 * R + 1 :=
            (clockGeom_le_nat p.r_pos.le p.r_lt_one.le R).trans (by linarith)
          nlinarith
      rw [stageClock_succ]
      push_cast
      simpa only [Nat.cast_add, Nat.cast_one] using hmain

end

end FirstPassageLinearTransport
